// SPDX-FileCopyrightText: (C) 2026 Deskflow Developers
// SPDX-License-Identifier: GPL-2.0-only WITH LicenseRef-OpenSSL-Exception
import Foundation
import FileProvider

// Group.swift is generated by deploy/mac/build-file-provider.py.
func storage() throws -> URL {
    guard let url = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: fileGroup) else {
        throw NSError(domain: NSCocoaErrorDomain, code: NSFileReadNoPermissionError)
    }
    return url
}

struct Entry: Decodable {
    let path: String
    let directory: Bool
    let size: String
    let revision: String?
    let sha256: String?
}
struct Offer: Decodable {
    let version: Int
    let expires: String
    let entries: [Entry]
}
func offerURL(_ id: String) throws -> URL {
    guard id.count == 64, id.allSatisfy({ $0.isHexDigit && !$0.isUppercase }) else {
        throw NSFileProviderError(.noSuchItem)
    }
    return try storage().appendingPathComponent("offers", isDirectory: true)
        .appendingPathComponent(id, isDirectory: true).appendingPathComponent("offer.json")
}
func loadOffer(_ id: String) throws -> (Offer, Data) {
    let bytes = try Data(contentsOf: offerURL(id))
    guard bytes.count <= 1_048_576 else { throw NSFileProviderError(.noSuchItem) }
    let offer = try JSONDecoder().decode(Offer.self, from: bytes)
    guard [1, 2].contains(offer.version), !offer.entries.isEmpty, offer.entries.count <= 4096 else {
        throw NSFileProviderError(.noSuchItem)
    }
    return (offer, bytes)
}
func entryIndex(_ id: NSFileProviderItemIdentifier, _ offer: Offer) -> Int? {
    guard id.rawValue.hasPrefix("entry-"), let i = Int(id.rawValue.dropFirst(6)),
          offer.entries.indices.contains(i) else { return nil }
    return i
}
func entryID(_ index: Int) -> NSFileProviderItemIdentifier { .init("entry-\(index)") }
